apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-demo
  template:
    metadata:
      labels:
        app: api-demo
    spec:
      containers:
      - name: api-demo
        image: container1189.azurecr.io/sampleapp:b5dacfb1a289f3a3b7cdc894c2c8d67adb9e8095
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-demo
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: api-demo
  type: LoadBalancer
